### 9.1 HttpException

Nest에서 제공하는 `HttpException` 를 이용해서 에러 처리를 할 수 있다. 아래 코드는 `cats`에 들어갔을 때 에러를 띄우는 예시이다 :

``` ts
  // cats/
  @Get()
  getCurrentCat() {
	throw new HttpException('api is broken', 401);
    return 'current cat';
  }
```

하지만 서비스의 형태에 따라 에러를 커스텀해야할 때가 있다. 또한 이때 에러 메시지의 재사용성을 활용하기 위해서 **HttpExceptionFilter** 를 이용할 수 있다.

### 9.2 HttpExceptionFilter

우선 나는 src/common/exception 폴더 위치에 `http-exception.filter.ts` 파일을 만들었다 :

``` ts
import {
  ArgumentsHost,
  Catch,
  ExceptionFilter,
  HttpException,
} from '@nestjs/common';
import { Request, Response } from 'express';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = exception.getStatus();
    const error = exception.getResponse() as
      | string
      | { error: string; statusCode: number; message: string | string[] };

    // 분기처리
    if (typeof error === 'string') {
      response.status(status).json({
        success: false,  // 예외처리가 발생된 것이므로 false
        timestamp: new Date().toISOString(),
        path: request.url,
        error,
      });
    } else {
      // nest 자체에서 발생하는 에러
      response.status(status).json({
        success: false,
        timestamp: new Date().toISOString(),
        ...error,
      });
    }
  }
}
```

위 코드는 [NestJS 공식문서](https://docs.nestjs.com/exception-filters)에서 작성된 `http-exception.filter.ts` 파일내의 코드를 수정한 코드이다. 

아래 코드는 위 코드의 일부분을 가져온 것이다 :

``` ts
    const error = exception.getResponse() as
      | string
      | { error: string; statusCode: number; message: string | string[] };
```

위 코드에서 `error`는 예외처리시 응답을 받는데 이때 `string` 으로 받을 수 있지만, nest 자체에서 JSON 으로 예외처리를 일으키므로 따로 타입을 지정하였다.

이 타입에 따라서 에러 상태를 json으로 전달하기 위해서 아래 코드와 같이 분기처리를 해주었다 :

``` ts
	// 분기처리
    if (typeof error === 'string') {
      response.status(status).json({
        success: false,  // 예외처리가 발생된 것이므로 false
        timestamp: new Date().toISOString(),
        path: request.url,
        error,
      });
    } else {
      // nest 자체에서 발생하는 에러
      response.status(status).json({
        success: false,
        timestamp: new Date().toISOString(),
        ...error,
      });
    }
```

이제 이 필터를 사용하기 위해서는 `@UseFilters()` 라는 데코레이터를 이용하여 컨트롤러와 연결할 수 있다. 물론 글로벌 설정도 할 수 있다.

우선 아래 코드는 데코레이터를 활용하여 컨트롤러에 연결한 모습이다 :

``` ts
@UseFilters(HttpExceptionFilter)
export class CatsController { ... }
```

컨트롤러 내에서 설정된 exception 인자를 `HttpExceptionFilter` 에서 받고, 이 클래스에서 설정한대로 에러 내용을 전달한다. 

만약 클래스 내에서 `throw new HttpException('api is broken', 401);` 라는 인자를 넘기게 되면, `HttpExceptionFilter` 내에서 `string` 을 처리하는 부분을 통해서 에러 처리를 한다.

글로벌 설정은 다음과 같이 할 수 있다 :

``` ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.useGlobalFilters(new HttpExceptionFilter());

  ...
}
```

위 코드는 `main.ts` 파일이고, 글로벌 설정을 통해서 따로 예외처리를 안한 곳에서 예외가 나면 nest가 자동으로 JSON 형태로 인자를 넘기게 된다.